version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - jabawack81
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.464.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.486.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.557.0
    - 1.563.0
    - 1.566.0
    - 1.570.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: cypress
    versions:
    - 6.7.1
    - 6.8.0
    - 7.0.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: netlify-plugin-cypress
    versions:
    - 1.10.0
    - 1.11.0
    - 1.7.0
    - 1.8.1
    - 1.9.2
    - 2.0.0
    - 2.1.0
