codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "app/"
        
    patch:
      default:
        target: auto
        threshold: 1%

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes

ignore:
  - "node_modules"
  - "dist"
  - "cypress"
  - "gulpfile.js"
  - "vite.config.js"
  - ".github"