[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.1"
  NPM_FLAGS = "--production=false"
  # Disable telemetry during builds
  NEXT_TELEMETRY_DISABLED = "1"

# Cypress plugin removed - tests run in GitHub Actions instead

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects (if needed in future)
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Deploy preview context
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    # Enable Cypress tests for deploy previews
    CYPRESS_baseUrl = "/"
    # Add a banner to deploy previews
    INCOMING_HOOK_TITLE = "Deploy Preview"
    INCOMING_HOOK_BODY = "A deploy preview for this pull request is ready!"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    # Enable Cypress tests for branch deploys
    CYPRESS_baseUrl = "/"

# Production context
[context.production]
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"