name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' && github.actor == 'dependabot[bot]') ||
      (github.event_name == 'pull_request_review' && github.event.pull_request.user.login == 'dependabot[bot]') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success')
    
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    - name: Auto-approve Dependabot PRs
      if: |
        (steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
         steps.metadata.outputs.update-type == 'version-update:semver-minor') &&
        steps.metadata.outputs.dependency-type != 'direct:production'
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Enable auto-merge for Dependabot PRs
      if: |
        (steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
         steps.metadata.outputs.update-type == 'version-update:semver-minor') &&
        steps.metadata.outputs.dependency-type != 'direct:production'
      run: |
        echo "Enabling auto-merge for ${{ steps.metadata.outputs.dependency-name }}"
        echo "Update type: ${{ steps.metadata.outputs.update-type }}"
        echo "From version: ${{ steps.metadata.outputs.previous-version }}"
        echo "To version: ${{ steps.metadata.outputs.new-version }}"
        gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Add comment for major updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-major'
      run: |
        gh pr comment "$PR_URL" --body "This is a major version update and requires manual review before merging.
        
        **Update type**: ${{ steps.metadata.outputs.update-type }}
        **Dependency**: ${{ steps.metadata.outputs.dependency-name }}
        **From**: ${{ steps.metadata.outputs.previous-version }}
        **To**: ${{ steps.metadata.outputs.new-version }}"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}