name: Visual Regression

on:
  workflow_dispatch:
    inputs:
      update_baselines:
        description: 'Update baseline images with current screenshots'
        required: false
        type: boolean
        default: false

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-liberation fonts-noto-color-emoji fonts-noto-cjk fonts-dejavu-core
        # Install Microsoft Core Fonts for better compatibility
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install -y ttf-mscorefonts-installer
        # Update font cache
        sudo fc-cache -f -v
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run visual regression tests
      run: npm test -- --spec="cypress/e2e/visual-regression.cy.js"
      env:
        CI: true
      
    - name: Upload visual regression report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: visual-regression-report
        path: |
          cypress-visual-screenshots/comparison/diff
          cypress-visual-screenshots/cypress-image-diff-html-report
        retention-days: 30
        
    - name: Update baseline images
      if: ${{ github.event.inputs.update_baselines == 'true' }}
      run: |
        cp -r cypress-visual-screenshots/comparison/comparison/* cypress-visual-screenshots/comparison/baseline/
        echo "Baseline images updated"
        
    - name: Commit updated baselines
      if: ${{ github.event.inputs.update_baselines == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: update visual regression baseline images'
        file_pattern: 'cypress-visual-screenshots/comparison/baseline/*'